apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openfga-system

# Create the namespace and install OpenFGA via Flux HelmRelease
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
