apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

# Optional network policies component
# Provides secure network isolation for auth-provider-openfga services

resources:
  - deny-all-default.yaml
  - metrics-network-policy.yaml
  - webhook-network-policy.yaml
  - allow-metrics-traffic.yaml
