apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Application-specific dependencies
# These are external services required by this specific application

resources:
  # OpenFGA authorization service (application-specific)
  - openfga
# Dependencies are services that:
# - Are required by this application
# - Could be shared across multiple instances of the same application
# - Are deployed independently of the application components
