---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - groups
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - groupmemberships
  - policybindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - groupmemberships/finalizers
  - policybindings/finalizers
  - protectedresources/finalizers
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - groupmemberships/status
  - policybindings/status
  - protectedresources/status
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - protectedresources
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects/finalizers
  verbs:
  - update
- apiGroups:
  - resourcemanager.miloapis.com
  resources:
  - projects/status
  verbs:
  - get
  - patch
  - update
