apiVersion: v1
kind: Service
metadata:
  name: openfga-authz-webhook
  labels:
    app.kubernetes.io/name: openfga-authz-webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: openfga-authz-webhook
  ports:
    - name: webhook-https
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
