apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

# Infrastructure services deployed via Flux
resources:
  - namespace.yaml
  - jetstack-helmrepository.yaml
  - cert-manager-helmrelease.yaml
  - cert-manager-csi-driver-helmrelease.yaml
