apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Install the CRDs from the Milo API that the controller manager needs
  - github.com/datum-cloud/milo/config/crd/bases
  # Base application components (includes namespace via transformer)
  - ../default

# Development-specific image configurations
images:
  - name: auth-provider-openfga
    newName: auth-provider-openfga
    newTag: dev
