apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-webhook
  labels:
    app.kubernetes.io/name: openfga-authz-webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga-authz-webhook
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: openfga-authz-webhook
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: authz-webhook
        image: auth-provider-openfga:latest
        imagePullPolicy: IfNotPresent
        args:
          - authz-webhook
          - --metrics-bind-address=:8080
          - --openfga-api-url=$(OPENFGA_API_URL)
          - --openfga-store-id=$(OPENFGA_STORE_ID)
          - --cert-dir=/etc/webhook/serving-certs
          - --cert-file=tls.crt
          - --key-file=tls.key
        env:
        - name: OPENFGA_API_URL
          value: openfga.openfga-system.svc.cluster.local:8081
        - name: OPENFGA_STORE_ID
          value: r01JVTBDT6NJ541P1JBT22GX4PR
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
          - containerPort: 9443
            name: webhook
            protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: webhook-server-tls
          mountPath: /etc/webhook/serving-certs
          readOnly: true
      volumes:
      - name: webhook-server-tls
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/common-name: openfga-authz-webhook
            csi.cert-manager.io/fs-group: "65532"
            csi.cert-manager.io/issuer-kind: ClusterIssuer
            csi.cert-manager.io/issuer-name: auth-provider-openfga-auth-provider-openfga-ca-cluster-issuer
            csi.cert-manager.io/dns-names: openfga-authz-webhook-service.system.svc,openfga-authz-webhook-service.system.svc.cluster.local
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
