apiVersion: v1
kind: Service
metadata:
  name: openfga-authz-webhook-service
  labels:
    app.kubernetes.io/name: openfga-authz-webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: openfga-authz-webhook
  ports:
  - name: webhook
    port: 9443
    targetPort: 9443
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
