apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-provider-openfga-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: auth-provider-openfga-ca
  secretName: auth-provider-openfga-ca-secret
  issuerRef:
    name: auth-provider-openfga-selfsigned-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: auth-provider-openfga-ca-cluster-issuer
spec:
  ca:
    secretName: auth-provider-openfga-ca-secret
