apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfga-store-init
  namespace: openfga-system
---
# Role in auth-provider-openfga-system to create the store-id ConfigMap
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfga-store-init
  namespace: auth-provider-openfga-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfga-store-init
  namespace: auth-provider-openfga-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfga-store-init
subjects:
  - kind: ServiceAccount
    name: openfga-store-init
    namespace: openfga-system
