apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- metrics-service.yaml
images:
- name: auth-provider-openfga
  newName: auth-provider-openfga
  newTag: latest
