apiVersion: v1
kind: Service
metadata:
  name: controller-manager-metrics
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: auth-provider-openfga
    app.kubernetes.io/component: metrics
spec:
  ports:
    - name: https
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: auth-provider-openfga
